services:
  - type: web
    name: staysync
    runtime: python
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
